### ISSUE TITLE
実行中にエラーが発生

### ISSUE THREAD

**Issue by asmka** [dff9th/discobot_AuthorExtract#2]
エラーメッセージ
```
Task exception was never retrieved
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/client.py:545> exception=KeyError('animated')>
Traceback (most recent call last):
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/client.py", line 547, in runner
    await self.start(*args, **kwargs)
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/client.py", line 511, in start
    await self.connect(reconnect=reconnect)
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/client.py", line 433, in connect
    await self._connect()
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/client.py", line 397, in _connect
    await self.ws.poll_event()
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/gateway.py", line 470, in poll_event
    await self.received_message(msg)
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/gateway.py", line 424, in received_message
    func(data)
  File "/home/discobot/.pyenv/versions/3.7.3/lib/python3.7/site-packages/discord/state.py", line 410, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
```

**Comment by asmka** [comment]
Bot実行サーバーの環境不足と判明．
pipでdiscord.pyをインストールし解決．

一旦クローズするが，将来的には同事象回避のためビルドスクリプトの導入が必須．
別途ビルドスクリプト用Issueを立ち上げることとする．
